export const SEND_CLIENT_RECEIPT_SUCCESS = 'SEND_CLIENT_RECEIPT_SUCCESS'
export const SEND_CLIENT_RECEIPT_FAILURE = 'SEND_CLIENT_RECEIPT_FAILURE'
export const CLIENT_RECEIPT_REQUEST = '/admin/api/emails/receipt'
